version: "3.8"
services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: resume-nginx
    depends_on:
      - face
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
  face:
    build:
      context: face/
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./face/src:/app/src
    command: npm run dev
    container_name: resume-face
    environment: {}
