version: "3.8"
services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: resume-nginx
    depends_on:
      - face_r
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: andrewkozinsky.ru,www.andrewkozinsky.ru
      LETSENCRYPT_HOST: andrewkozinsky.ru,www.andrewkozinsky.ru
  face_r:
    build:
      context: face_r/
      dockerfile: Dockerfile.server
    restart: unless-stopped
    command: npm run start
    container_name: resume-face
    environment: {}
networks:
  default:
    external:
      name: nginx-proxy
